### PR TITLE
Add CEL to K8sPSPCapabilities template

### PR DESCRIPTION
**Pull request by maxsmythe**
**What this PR does / why we need it**:

**Which issue(s) does this PR fix** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #541 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by JaydipGabani — COMMENTED** [review]
CEL looks good to me. We need to update template version and artifact-hub as well. `make generate-all` will do the job after updating template version. LGTM after these changes

**Comment by maxsmythe** [comment]
Bumped the minor version

**Review by JaydipGabani — APPROVED** [review]
LGTM

**Comment by JaydipGabani** [comment]
@maxsmythe should we use `snake_case` instead of `camelCase` for naming variables to be more consistent with variables in rego policies?

**Comment by maxsmythe** [comment]
@JaydipGabani

VAP appears to use camel case, and YAML params use camel case, so probably more consistent to stick with camel case.

Example from K8s documentation:

https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/#variable-composition

**Review by sozercan — APPROVED** [review]
Thank you! LGTM

**Pull request merged**
