### PR TITLE
Updating typos, inclusive verbiage

### PR DESCRIPTION
**Pull request by tahirraza**
**What this PR does / why we need it**:

Fixing few things in README:
- Typos
- Table spacing
- Inclusive terminology. Replaced whitelist with approved list

No issues to reference

**Special notes for your reviewer**:

Trivial changes to README.

### CODE REVIEW

**Review by sozercan — APPROVED** [review]
Thank you! LGTM

**Comment by sozercan** [comment]
@tahirraza looks like DCO needs to be signed. You can find instructions at https://open-policy-agent.github.io/gatekeeper/website/docs/help/#developer-certification-of-origin-dco

**Comment by tahirraza** [comment]
Thanks @sozercan - good now?

**Comment by sozercan** [comment]
@tahirraza please make sure to run the generate steps to generate docs too

**Comment by tahirraza** [comment]
okay did another commit for docs

**Pull request merged**
