### PR TITLE
chore: reduce code duplication

### PR DESCRIPTION
**Pull request by choeffer**

### CODE REVIEW

**Comment by maxsmythe** [comment]
Thanks for the PR!

Could you fix the failing DCO check per the instructions under `Details`?

**Comment by maxsmythe** [comment]
closing this PR due to inactivity. Please re-open if you want to pursue merging it.

**Comment by choeffer** [comment]
@maxsmythe sorry for the huge delay, I have signed-off the commit. Anything else which is missing?

**Comment by maxsmythe** [comment]
You'll also need to update the source Rego for the template: https://github.com/open-policy-agent/gatekeeper-library/blob/master/src/general/allowedrepos/src.rego

**Pull request closed without merging**
