### PR TITLE
Added policy to block LoadBalancer services

### PR DESCRIPTION
**Pull request by sstoyanovucsd**
In some environments we'd like the cluster customers to use the pre-provisioned Ingress Controllers to expose their workloads to the outside world.  This policy allows the cluster administrator to block the creation of LoadBalancer services, which can lead to provisioning costly cloud resources (LBs).  This policy along with the one for NodePorts, on which this one is based, also prevent customers from exposing their workload in an unexpected and potentially unmonitored way, which can present a security issue.

### CODE REVIEW

**Review by maxsmythe — CHANGES_REQUESTED** [review]
Thanks for the PR! Can you include the Rego source and templated template to mirror the rest of the templates?

IMO no need for Rego tests given the suite test should cover things sufficiently (not sure if others will agree).

Here is a sample PR that shows what the templated template stuff looks like: #214

**Comment by sstoyanovucsd** [comment]
Thanks for the pointers @maxsmythe.  Added the things you requested and also rego tests.

**Review by maxsmythe — APPROVED** [review]
LGTM, thanks for the PR!

**Review by ritazh — APPROVED** [review]
LGTM

Thanks for the PR!

**Pull request merged**
