### PR TITLE
Add explanations to ConstraintTemplates

### PR DESCRIPTION
**Pull request by willbeason**
Clarify the purpose of several templates and their limitations.

### CODE REVIEW

**Review by maxsmythe — APPROVED** [review]
LGTM

**Review by julianKatz — APPROVED** [review]

**Comment by willbeason** [comment]
@mkorfgoogle?

**Review by sozercan — APPROVED** [review]
LGTM

**Comment by mkorfgoogle** [comment]
Looks good.

**Comment by mkorfgoogle** [comment]
LGTM

**Pull request merged**
