### PR TITLE
Fix: verifydepricatedapi not showing up in website sidebar

### PR DESCRIPTION
**Pull request by JaydipGabani**
Signed-off-by: Jaydip Gabani <gabanijaydip@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) does this PR fix** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by nilekhc — APPROVED** [review]
LGTM

**Comment by nilekhc** [comment]
cc @maxsmythe @sozercan

**Review by ritazh — APPROVED** [review]
LGTM

**Review by maxsmythe — APPROVED** [review]
Short-term fix LGTM, but how did this happen? Do we require manual maintenance of the sidebar? Can we mitigate the chances of this recurring?

**Comment by nilekhc** [comment]
> Short-term fix LGTM, but how did this happen? Do we require manual maintenance of the sidebar? Can we mitigate the chances of this recurring?

Yeah. For the sidebar, we need to add the entry manually. I opened https://github.com/open-policy-agent/gatekeeper-library/issues/293 to automate this.

**Review by sozercan — APPROVED** [review]

**Pull request merged**
