### PR TITLE
Fix `explictly` typo

### PR DESCRIPTION
**Pull request by JRBANCEL**
**What this PR does / why we need it**:
Simple typo fix.

**Which issue(s) does this PR fix**
N/A

**Special notes for your reviewer**:
Include a spellchecker in the CI/CD flow?

### CODE REVIEW

**Review by apeabody — COMMENTED** [review]
Thanks for the contribution @JRBANCE!

To update the template, can you please:
- Update the src file here: https://github.com/open-policy-agent/gatekeeper-library/blob/master/src/pod-security-policy/forbidden-sysctls/src.rego#L14
- Bump the version to `1.1.1` here: https://github.com/open-policy-agent/gatekeeper-library/pull/317/files#diff-2f0ae5e8ed4ef9f5ad5bf3a1e9147cd425831733ceeb154cb6d59c0ea6811dbaR7
- And then run `make generate-all` to build out the new template, docs, etc.

**Comment by JRBANCEL** [comment]
Done.

**Comment by JRBANCEL** [comment]
@apeabody does it look good?

**Comment by apeabody** [comment]
> @apeabody does it look good?

Thanks @JRBANCEL - I see the generated content!  Currently the DCO check is blocking, can you please add the required Signed-of-by line, git can typically add it with `git commit --amend -s`.  More details: https://github.com/open-policy-agent/gatekeeper-library/pull/317/checks

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @JRBANCEL LGTM!

**Comment by JRBANCEL** [comment]
Cool. Am I supposed to merge the PR?
I don't have write access.

**Pull request merged**
