### PR TITLE
Fix k8spsphostfilesystem path matching

### PR DESCRIPTION
**Pull request by philsphicas**
This change updates the path matching logic to correctly handle "/",
which should match all paths.

Fixes https://github.com/open-policy-agent/gatekeeper-library/issues/96

### CODE REVIEW

**Comment by philsphicas** [comment]
I signed it

**Review by maxsmythe — CHANGES_REQUESTED** [review]
Thanks for the PR!

The code looks good, can you make sure the changes are also included in:

https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/pod-security-policy/host-filesystem/template.yaml

?

Unfortunately, we haven't yet automated the pipeline for doing this.

**Comment by philsphicas** [comment]
> The code looks good, can you make sure the changes are also included in:
> 
> https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/pod-security-policy/host-filesystem/template.yaml
> 

Done.

Thanks for reviewing, sorry I missed that.

**Review by maxsmythe — APPROVED** [review]
Absolutely. No worries on missing that, things should be more automated than they currently are, thank you for the PR!

**Review by ritazh — APPROVED** [review]

**Pull request merged**
