### PR TITLE
Update sync YAML config file

### LINKED ISSUE #42: Update Config to include the latest Kubernetes 1.19 API group
Update the ReplicateData config to include the latest Kubernetes 1.19 API group version for ingress.
```yaml
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "gatekeeper-system"
spec:
  sync:
    syncOnly:
      - group: "extensions"
        version: "v1beta1"
        kind: "Ingress"
      - group: "networking.k8s.io"
        version: "v1beta1"
        kind: "Ingress"
     - group: "networking.k8s.io"
        version: "v1"
        kind: "Ingress"
```
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#ingress-v1-networking-k8s-io
https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/service/networking/minimal-ingress.yaml

### PR DESCRIPTION
**Pull request by JonnieDoe**
k8s 1.19 now support Ingress as an internal object v1: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#ingress-v1-networking-k8s-io

Closes #42

### CODE REVIEW

**Review by sozercan — APPROVED** [review]
LGTM

**Comment by maxsmythe** [comment]
Thanks for the submission!

LGTM, but could you fix the DCO check failure and sign the CLA? Otherwise we can't merge the PR.

**Comment by JonnieDoe** [comment]
> Thanks for the submission!
> 
> LGTM, but could you fix the DCO check failure and sign the CLA? Otherwise we can't merge the PR.

I will make the changes.

**Comment by JonnieDoe** [comment]
> Thanks for the submission!
> 
> LGTM, but could you fix the DCO check failure and sign the CLA? Otherwise we can't merge the PR.

@maxsmythe Do we have the CLA signing procedure documented somewhere? Some codebases use EasyCLA whereas this repo does not. Thanks.

**Comment by sozercan** [comment]
@JonnieDoe looks like it is `commit missing GitHub user` error, I think you need to add your user to `.gitconfig`

**Comment by JonnieDoe** [comment]
> @JonnieDoe looks like it is `commit missing GitHub user` error, I think you need to add your user to `.gitconfig`
> https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

Thanks for the suggestion. There was a problem with the account linking. After signing the CLA, I still have to fix something. I will take a look tomorrow.

**Comment by maxsmythe** [comment]
Closing this as it's old and the CLA has not been signed.

Please re-open if you'd like to resume submitting this PR.

**Pull request closed without merging**
