### PR TITLE
fix proc-mount rego multiple output with same input

### LINKED ISSUE #311: proc-mount rego has potential bug
If parameter `procMount` is invalid, for example `invalid`, the function `get_allowed_proc_mount` will return different result with the same input.
https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/pod-security-policy/proc-mount/template.yaml
`eval_conflict_error: functions must not produce multiple outputs for same inputs`

The issue might be avoid by enum parameter value, but it is still one potential bug in the rego langueage.

### PR DESCRIPTION
**Pull request by fseldow**
**What this PR does / why we need it**:
Rego bug if the parameter input is invalid, it will report `eval_conflict_error: functions must not produce multiple outputs for same inputs`
The situation might be avoid by parameter enum. The pr here is to improve the rego to avoid such situation

**Which issue(s) does this PR fix** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #311

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ritazh** [comment]
Please run 'make generate generate-website-docs generate-artifacthub-artifacts' to generate the templates and docs

**Review by maxsmythe — APPROVED** [review]
LGTM, thank you!

**Comment by maxsmythe** [comment]
It looks like this command needs to be run: `Please run 'make generate generate-website-docs generate-artifacthub-artifacts' to generate the templates and docs`

**Review by ritazh — APPROVED** [review]
LGTM

**Pull request merged**
