### PR TITLE
feat: update require-sync

### PR DESCRIPTION
**Pull request by apeabody**
**What this PR does / why we need it**:
update `require-sync` - prerequisite for #330 
* GO 1.20
* open-policy-agent/frameworks/constraint v0.9.0
* open-policy-agent/gatekeeper 3.11.1
* k8s.io/apimachinery v0.24.13 - supersedes #338 
* github.com/docker/docker v20.10.24
* lint/fmt

### CODE REVIEW

**Review by maxsmythe — APPROVED** [review]
LGTM

**Comment by apeabody** [comment]
Hi @sozercan - This PR will supersede https://github.com/open-policy-agent/gatekeeper-library/pull/338

**Comment by apeabody** [comment]
Hi @nilekhc - Would you be able to get a look so we can get this merged?  Thanks!

**Review by nilekhc — APPROVED** [review]
LGTM

**Pull request merged**
