### PR TITLE
Update PDB policy

### PR DESCRIPTION
**Pull request by pallav-G**
**What this PR does / why we need it**:

**https://github.com/open-policy-agent/gatekeeper-library/issues/343*:

### CODE REVIEW

**Comment by pallav-G** [comment]
@apeabody Done 👍

**Comment by pallav-G** [comment]
@apeabody all checks are passing, can you please take a look

**Review by JaydipGabani — CHANGES_REQUESTED** [review]
@pallav-G Please add examples with PDB that enforce the number of replicas based on percentage that executes the changes you are introducing.

**Comment by pallav-G** [comment]
@JaydipGabani Done👍

**Comment by pallav-G** [comment]
@JaydipGabani does it look good now?

**Review by JaydipGabani — APPROVED** [review]
LGTM, thanks again. Apologies for the delay

**Pull request closed without merging**
