### PR TITLE
Update Kuberentes version for integration tests

### PR DESCRIPTION
**Pull request by phillebaba**
Updates the Kubernetes version in the integration tests to unblock #191.

### CODE REVIEW

**Review by sozercan — APPROVED** [review]
LGTM

**Review by sozercan — CHANGES_REQUESTED** [review]
looks like integration tests are failing

**Comment by sozercan** [comment]
Looks like there's a behavior change from 1.21 -> 1.23, allowedrepos policy with disallow initContainer pod fails Kubernetes validation since you can't have initContainers without containers anymore.

https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/allowedrepos/samples/repo-must-be-openpolicyagent/disallowed_initcontainer.yaml

**Comment by ritazh** [comment]
@phillebaba Thank you for opening this PR. Do you have time to work on the suggested changes? If not, we can close this in favor of https://github.com/open-policy-agent/gatekeeper-library/pull/196. WDYT?

**Comment by phillebaba** [comment]
@ritazh lets close this and let #196 fix it

**Pull request closed without merging**
