### PR TITLE
Add test suites for second half of PSP policies

### PR DESCRIPTION
**Pull request by maxsmythe**
Signed-off-by: Max Smythe <smythe@google.com>

### CODE REVIEW

**Review by willbeason — APPROVED** [review]
Did you test with "gator test ./..."?

**Comment by maxsmythe** [comment]
yep!

@sozercan @shomron @ritazh LGTY?

**Review by julianKatz — APPROVED** [review]

**Comment by maxsmythe** [comment]
We'll need to add `metadata.name` per https://github.com/open-policy-agent/gatekeeper-library/issues/156

**Comment by maxsmythe** [comment]
Added metadata.name to all pre-existing suites, still LGTY @julianKatz @willbeason ?

**Comment by willbeason** [comment]
> Added metadata.name to all pre-existing suites, still LGTY @julianKatz @willbeason ?

My nit would be to use hyphens to separate words to make them more readable. Not a blocker though, still LGTM.

**Comment by julianKatz** [comment]
> Added metadata.name to all pre-existing suites, still LGTY @julianKatz @willbeason ?

LGTM

**Review by ritazh — APPROVED** [review]

**Pull request merged**
