### PR TITLE
Add v1 Ingress version to uniqueingresshost sync object

### PR DESCRIPTION
**Pull request by arapulido**
Ingress went GA, but the sync object for the unique ingress host policy is only syncing previous API versions of the object.

This PR updates the sync object to include `v1` of the API

### CODE REVIEW

**Review by sozercan — APPROVED** [review]
Thank you! LGTM

**Comment by sozercan** [comment]
@arapulido looks like generate is failing, please run `make generate generate-website-docs generate-artifacthub-artifacts` and push the changes.

**Comment by arapulido** [comment]
@sozercan done! all tests passing now

**Review by maxsmythe — APPROVED** [review]
LGTM

**Pull request merged**
